"""SQLite storage for StudyGenie.

Tables:
  courses  — one row per class (name, exam date)
  topics   — study topics inside a course, each with a difficulty 1-5
  sessions — planned/completed study blocks generated by the scheduler
"""
import sqlite3
from pathlib import Path

SCHEMA = """
CREATE TABLE IF NOT EXISTS courses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    exam_date TEXT NOT NULL,          -- YYYY-MM-DD
    created_at TEXT DEFAULT (date('now'))
);
CREATE TABLE IF NOT EXISTS topics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    difficulty INTEGER NOT NULL DEFAULT 3 CHECK (difficulty BETWEEN 1 AND 5),
    done INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    topic_id INTEGER REFERENCES topics(id) ON DELETE SET NULL,
    planned_date TEXT NOT NULL,       -- YYYY-MM-DD
    minutes INTEGER NOT NULL,
    completed INTEGER NOT NULL DEFAULT 0
);
"""


def connect(db_path):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db(db_path):
    with connect(db_path) as conn:
        conn.executescript(SCHEMA)


# --- courses ---

def add_course(db_path, name, exam_date):
    with connect(db_path) as conn:
        cur = conn.execute(
            "INSERT INTO courses (name, exam_date) VALUES (?, ?)",
            (name.strip(), exam_date),
        )
        return cur.lastrowid


def list_courses(db_path):
    with connect(db_path) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM courses ORDER BY exam_date")]


def get_course(db_path, course_id):
    with connect(db_path) as conn:
        row = conn.execute(
            "SELECT * FROM courses WHERE id = ?", (course_id,)).fetchone()
        return dict(row) if row else None


# --- topics ---

def add_topic(db_path, course_id, title, difficulty=3):
    difficulty = max(1, min(5, int(difficulty)))
    with connect(db_path) as conn:
        cur = conn.execute(
            "INSERT INTO topics (course_id, title, difficulty) VALUES (?, ?, ?)",
            (course_id, title.strip(), difficulty),
        )
        return cur.lastrowid


def list_topics(db_path, course_id):
    with connect(db_path) as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM topics WHERE course_id = ? ORDER BY difficulty DESC, id",
            (course_id,))]
